spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

datasource:
url: jdbc:postgresql://ec2-54-204-96-190.compute-1.amazonaws.com:5432/ddicdujp50rls7?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
driver-class-name: 
username: 
password: 
