spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

datasource:
<<<<<<< HEAD
url: jdbc:postgres://tymnbxclkymofd:83e754e4b2f9c2cf5237b9d839c14ee588289a4db74bec0d83735f816d984e72@ec2-3-212-143-188.compute-1.amazonaws.com:5432/d7k236al1qr8c1
driver-class-name: org.postgresql.Driver
username: tymnbxclkymofd
password: 83e754e4b2f9c2cf5237b9d839c14ee588289a4db74bec0d83735f816d984e72